project:
  type: book
  output-dir: _book

book:
  title: "The Celestial Curia"
  subtitle: "The Master Book of Traditional Astrology"
  author: "Andrew Darcy"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - complete_reference.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: scrbook
    keep-tex: true
    toc: true
    number-sections: true
  epub:
    toc: true
    number-sections: true
